from tkinter import *

def init(root):
    firstColumnText = Label(root, text = "Fishing")
    firstColumnText.grid(row=0, column=0, pady=(3, 0))
    firstColumn = LabelFrame(root)
    firstColumn.grid(row=1, column=0, padx=(10, 0), pady=(0, 5))
    firstColumnFirstRowHeaderText = Label(firstColumn, text = "Rectangle position (px)")
    firstColumnFirstRowHeaderText.grid(row=0, column=0)
    firstColumnFirstRow = LabelFrame(firstColumn)
    firstColumnFirstRow.grid(row=1, column=0, padx=(10))
    firstColumnFirstRowX = Label(firstColumnFirstRow, height=1)
    firstColumnFirstRowX.grid(row=0, column=0, padx=(5))
    firstColumnFirstRowXText = Label(firstColumnFirstRowX, text="X:", anchor="s")
    firstColumnFirstRowXText.grid(row=0, column=0, pady=(20, 0))
    firstColumnFirstRowXScale = Scale(firstColumnFirstRowX, from_=0, to=5120, orient=HORIZONTAL)
    firstColumnFirstRowXScale.grid(row=0, column=1)
    firstColumnFirstRowXEntry = Text(firstColumnFirstRowX, width=4, height=1)
    firstColumnFirstRowXEntry.grid(row=0, column=2, pady=(20, 0))
    firstColumnFirstRowY = Label(firstColumnFirstRow, height=1)
    firstColumnFirstRowY.grid(row=1, column=0)
    firstColumnFirstRowYText = Label(firstColumnFirstRowY, text="Y:", anchor="s")
    firstColumnFirstRowYText.grid(row=0, column=0, pady=(20, 0))
    firstColumnFirstRowYScale = Scale(firstColumnFirstRowY, from_=0, to=2160, orient=HORIZONTAL)
    firstColumnFirstRowYScale.grid(row=0, column=1)
    firstColumnFirstRowYEntry = Text(firstColumnFirstRowY, width=4, height=1)
    firstColumnFirstRowYEntry.grid(row=0, column=2, pady=(20, 0))
    firstColumnSecondRowHeaderText = Label(firstColumn, text = "Rectangle attributes (px)")
    firstColumnSecondRowHeaderText.grid(row=2, column=0)
    firstColumnSecondRow = LabelFrame(firstColumn)
    firstColumnSecondRow.grid(row=3, column=0, padx=(10))
    firstColumnSecondRowX = Label(firstColumnSecondRow, height=1)
    firstColumnSecondRowX.grid(row=0, column=0, padx=(5))
    firstColumnSecondRowXText = Label(firstColumnSecondRowX, text="X:", anchor="s")
    firstColumnSecondRowXText.grid(row=0, column=0, pady=(20, 0))
    firstColumnSecondRowXScale = Scale(firstColumnSecondRowX, from_=0, to=5120, orient=HORIZONTAL)
    firstColumnSecondRowXScale.grid(row=0, column=1)
    firstColumnSecondRowXEntry = Text(firstColumnSecondRowX, width=4, height=1)
    firstColumnSecondRowXEntry.grid(row=0, column=2, pady=(20, 0))
    firstColumnSecondRowY = Label(firstColumnSecondRow, height=1)
    firstColumnSecondRowY.grid(row=1, column=0)
    firstColumnSecondRowYText = Label(firstColumnSecondRowY, text="Y:")
    firstColumnSecondRowYText.grid(row=0, column=0, pady=(20, 0))
    firstColumnSecondRowYScale = Scale(firstColumnSecondRowY, from_=0, to=2160, orient=HORIZONTAL)
    firstColumnSecondRowYScale.grid(row=0, column=1)
    firstColumnSecondRowYEntry = Text(firstColumnSecondRowY, width=4, height=1)
    firstColumnSecondRowYEntry.grid(row=0, column=2, pady=(10, 0))
    firstColumnThirdRow = LabelFrame(firstColumn)
    firstColumnThirdRow.grid(row=4, column=0, pady=(3, 0))
    firstColumnThirdRowButton = Button(firstColumnThirdRow, text = "Show rectangle")
    firstColumnThirdRowButton.grid(row=4, column=0, padx=(40))

    secondColumnText = Label(root, text = "Repairing")
    secondColumnText.grid(row=0, column=1, pady=(3, 0))
    secondColumn = LabelFrame(root)
    secondColumn.grid(row=1, column=1, padx=(10, 0), pady=(0, 93))
    secondColumnFirstRowHeaderText = Label(secondColumn, text = "Click position (px)")
    secondColumnFirstRowHeaderText.grid(row=0, column=0)
    secondColumnFirstRow = LabelFrame(secondColumn)
    secondColumnFirstRow.grid(row=1, column=0, padx=(10))
    secondColumnFirstRowX = Label(secondColumnFirstRow, height=1)
    secondColumnFirstRowX.grid(row=0, column=0, padx=(5))
    secondColumnFirstRowXText = Label(secondColumnFirstRowX, text="X:", anchor="s")
    secondColumnFirstRowXText.grid(row=0, column=0, pady=(20, 0))
    secondColumnFirstRowXScale = Scale(secondColumnFirstRowX, from_=0, to=5120, orient=HORIZONTAL)
    secondColumnFirstRowXScale.grid(row=0, column=1)
    secondColumnFirstRowXEntry = Text(secondColumnFirstRowX, width=4, height=1)
    secondColumnFirstRowXEntry.grid(row=0, column=2, pady=(20, 0))
    secondColumnFirstRowY = Label(secondColumnFirstRow, height=1)
    secondColumnFirstRowY.grid(row=1, column=0)
    secondColumnFirstRowYText = Label(secondColumnFirstRowY, text="Y:")
    secondColumnFirstRowYText.grid(row=0, column=0, pady=(20, 0))
    secondColumnFirstRowYScale = Scale(secondColumnFirstRowY, from_=0, to=2160, orient=HORIZONTAL)
    secondColumnFirstRowYScale.grid(row=0, column=1)
    secondColumnFirstRowYEntry = Text(secondColumnFirstRowY, width=4, height=1)
    secondColumnFirstRowYEntry.grid(row=0, column=2, pady=(20, 0))
    secondColumnSecondRow = LabelFrame(secondColumn)
    secondColumnSecondRow.grid(row=3, column=0)
    secondColumnSecondRowCheckText = Label(secondColumnSecondRow, text="Enable repairs:")
    secondColumnSecondRowCheckText.grid(row=0, column=0, padx=(0, 45))
    secondColumnSecondRowCheckButton = Checkbutton(secondColumnSecondRow)
    secondColumnSecondRowCheckButton.grid(row=0, column=1, padx=(0, 17))
    secondColumnSecondRowYEntry = Text(firstColumnSecondRowY, width=4, height=1)
    secondColumnSecondRowYEntry.grid(row=0, column=2, pady=(10, 0))
    secondColumnThirdRow = LabelFrame(secondColumn)
    secondColumnThirdRow.grid(row=4, column=0, pady=(3, 0))
    secondColumnSecondRowButton = Button(secondColumnThirdRow, text = "Show repair position")
    secondColumnSecondRowButton.grid(row=0, column=0, padx=(26, 27), pady=(2, 4))

    secondRow = LabelFrame(root)
    secondRow.grid(row=3, columnspan=2, padx=(10, 0), pady=(0, 5))
    secondRowButton = Button(secondRow, text = "Start fishing", font=18)
    secondRowButton.grid(row=0, column=0)